name: dbt BigQuery CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt-bigquery
        run: pip install dbt-bigquery

      # ✅ FIX: move into the correct folder before running dbt
      - name: Change directory to ga4_attribution
        run: cd ga4_attribution && ls -la

      # ✅ Setup GCP credentials
      - name: Set up GCP credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/keyfile.json
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > $HOME/keyfile.json
          cat $HOME/keyfile.json | jq .project_id


      # ✅ Run dbt commands inside correct folder
      - name: Run dbt debug
        working-directory: ga4_attribution
        run: dbt debug

      - name: Run dbt build (run + test)
        working-directory: ga4_attribution
        run: |
          dbt deps
          dbt build
